<?php

namespace BinktermPhpAx25Kiss;

/**
 * Bridge configuration loaded from a JSON file.
 *
 * See config.example.json for all available options.
 */
class BridgeConfig
{
    /** BBS station callsign used as the source when transmitting AX.25 frames. */
    public readonly string $mycall;

    /**
     * Node ID registered in the BBS admin panel (Admin > Packet BBS > Nodes).
     * Typically the same as $mycall.
     */
    public readonly string $bridgeNodeId;

    /** Bearer API key generated by the BBS for this node. */
    public readonly string $apiKey;

    /** BBS base URL without trailing slash (e.g. http://192.168.1.10:1244). */
    public readonly string $bbsUrl;

    /** TNC connection type: "tcp" or "serial". */
    public readonly string $tncType;

    /** TCP hostname for software TNCs such as Direwolf. */
    public readonly string $tncHost;

    /** TCP port for software TNCs (Direwolf default: 8001). */
    public readonly int $tncPort;

    /** Serial device path for hardware TNCs (e.g. /dev/ttyUSB0). */
    public readonly string $serialDevice;

    /** Serial baud rate (default: 1200). */
    public readonly int $serialBaud;

    /** Seconds between outbound queue polls for active callsigns. */
    public readonly int $pollIntervalSec;

    /** Inactivity window (seconds) before a callsign is dropped from the poll list. */
    public readonly int $activeTtlSec;

    /**
     * Maximum AX.25 information field size in bytes.
     *
     * Standard TNCs support up to 256 bytes; many are configured for larger
     * frames. Long BBS responses are split into chunks of this size.
     */
    public readonly int $maxFrameInfo;

    /** Log level string: DEBUG, INFO, WARNING, ERROR. */
    public readonly string $logLevel;

    /** Path to log file, or empty string to disable file logging. */
    public readonly string $logFile;

    /** Also echo log output to stdout. */
    public readonly bool $logEcho;

    public static function fromFile(string $path): self
    {
        if (!file_exists($path)) {
            throw new \RuntimeException("Config file not found: {$path}");
        }

        $json = file_get_contents($path);
        $data = json_decode($json, true);

        if (!is_array($data)) {
            throw new \RuntimeException("Invalid JSON in config file: {$path}");
        }

        return self::fromArray($data);
    }

    public static function fromArray(array $data): self
    {
        $cfg = new self();

        $cfg->mycall        = strtoupper(trim($data['mycall'] ?? ''));
        $cfg->bridgeNodeId  = strtoupper(trim($data['bridge_node_id'] ?? $cfg->mycall));
        $cfg->apiKey        = trim($data['api_key'] ?? '');
        $cfg->bbsUrl        = rtrim(trim($data['bbs_url'] ?? ''), '/');

        $tnc                = $data['tnc'] ?? [];
        $cfg->tncType       = strtolower($tnc['type'] ?? 'tcp');
        $cfg->tncHost       = $tnc['host'] ?? 'localhost';
        $cfg->tncPort       = (int)($tnc['port'] ?? 8001);
        $cfg->serialDevice  = $tnc['device'] ?? '/dev/ttyUSB0';
        $cfg->serialBaud    = (int)($tnc['baud'] ?? 1200);

        $cfg->pollIntervalSec = (int)($data['poll_interval_sec'] ?? 15);
        $cfg->activeTtlSec    = (int)($data['active_ttl_sec'] ?? 900);
        $cfg->maxFrameInfo    = (int)($data['max_frame_info'] ?? 236);

        $cfg->logLevel = $data['log_level'] ?? 'INFO';
        $cfg->logFile  = $data['log_file'] ?? 'ax25_kiss_bridge.log';
        $cfg->logEcho  = (bool)($data['log_echo'] ?? false);

        if ($cfg->mycall === '') {
            throw new \RuntimeException("Config: 'mycall' is required");
        }
        if ($cfg->apiKey === '') {
            throw new \RuntimeException("Config: 'api_key' is required");
        }
        if ($cfg->bbsUrl === '') {
            throw new \RuntimeException("Config: 'bbs_url' is required");
        }

        return $cfg;
    }

    private function __construct() {}
}
